name: mockitory
description: A new Flutter package project.
version: 0.0.1+1
homepage: https://github.com/jarekb123/mockitory

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.16.8