name: flutter_mockitory
description: Mock data layer with Flutter widgets
version: 2.0.1
homepage: https://github.com/jarekb123/mockitory

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockitory: 
    path: ../mockitory

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
